services:
  flet-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - contact-data:/data
      - type: bind
        source: .
        target: /app

volumes:
  contact-data:
