services:
  flet-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_FROM
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - LOGGING_LEVEL
      - DEV_MODE
      - SUPPORTED_LOCATIONS_MODE
      - UPPORTED_LOCATIONS_FILE_PATH
      - FL_FILE_PATH
      - ZOOM_FILE_PATH

    volumes:
      - contact-data:/data

volumes:
  contact-data:
